#!/usr/bin/env node
/**
 * Mirror the webfonts locally instead of loading them from Google.
 *
 * Google Fonts costs two extra origins (DNS + TLS + a render-blocking
 * stylesheet) before the first paint, is blocked on some networks, and puts a
 * third party in the critical path of a site that is otherwise entirely
 * static. Self-hosting removes all of that and the files then live as long as
 * the repository does.
 *
 * Google already splits each family by unicode-range, so there is nothing to
 * subset by hand: this fetches the stylesheet it would serve, keeps only the
 * ranges this site actually needs, downloads those .woff2 files and rewrites
 * the @font-face rules to point at them.
 *
 * IBM Plex is SIL OFL 1.1, which permits redistribution.
 *
 * Re-run only when the font stack changes:  node tools/fetch-fonts.mjs
 */

import { writeFileSync, mkdirSync, existsSync, readFileSync, readdirSync, unlinkSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(root, 'assets/fonts');
const CSS_OUT = join(root, 'assets/css/fonts.css');

/*
 * IBM Plex Sans is deliberately absent: IBM Plex Sans Thai carries the same
 * Latin design, and canvas measurement of identical strings gave identical
 * advance widths to the decimal. Shipping both meant every Thai page pulled
 * two families to draw one alphabet.
 */
const HREF = 'https://fonts.googleapis.com/css2'
  + '?family=IBM+Plex+Mono:wght@400;500'
  + '&family=IBM+Plex+Sans+Thai:wght@400;500;600'
  + '&display=swap';

// A Thai/English site needs Latin and Thai. Google also offers cyrillic,
// greek and vietnamese; downloading those would be dead weight.
const KEEP = ['latin', 'latin-ext', 'thai'];

// woff2 needs a browser UA, otherwise Google serves the much larger ttf.
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
  + 'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const css = await (await fetch(HREF, { headers: { 'User-Agent': UA } })).text();

/** Google emits `/* latin *\/` before each block; that comment names the range. */
const blocks = css.split('/*').slice(1).map((chunk) => {
  const [name, ...rest] = chunk.split('*/');
  return { subset: name.trim(), body: rest.join('*/') };
});

mkdirSync(OUT_DIR, { recursive: true });

const out = [
  '/* IBM Plex — SIL Open Font License 1.1.',
  '   Generated by tools/fetch-fonts.mjs; do not edit by hand. */',
  '',
];
let kept = 0;
let bytes = 0;
const wanted = new Set();

for (const { subset, body } of blocks) {
  if (!KEEP.includes(subset)) continue;

  const url = body.match(/url\((https:\/\/fonts\.gstatic\.com[^)]+\.woff2)\)/)?.[1];
  const family = body.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = body.match(/font-weight:\s*(\d+)/)?.[1];
  if (!url || !family || !weight) continue;

  const file = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}-${subset}.woff2`;
  const abs = join(OUT_DIR, file);

  if (!existsSync(abs)) {
    const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    writeFileSync(abs, buf);
  }
  wanted.add(file);
  bytes += readFileSync(abs).length;
  kept += 1;

  out.push(`/* ${family} ${weight} — ${subset} */`);
  out.push(body.replace(/url\(https:\/\/fonts\.gstatic\.com[^)]+\.woff2\)/,
    `url(/assets/fonts/${file}) format('woff2')`).trim());
  out.push('');
}

// Drop anything left behind by an earlier font stack, so assets/fonts/ only
// ever holds what fonts.css actually references.
for (const file of readdirSync(OUT_DIR)) {
  if (file.endsWith('.woff2') && !wanted.has(file)) {
    unlinkSync(join(OUT_DIR, file));
    console.log(`removed stale ${file}`);
  }
}

writeFileSync(CSS_OUT, `${out.join('\n')}\n`);
console.log(`${kept} font files, ${(bytes / 1024).toFixed(0)} KB total → assets/fonts/`);
console.log(`stylesheet → assets/css/fonts.css`);
